import Link from "next/link";
import { Activity, AlertTriangle, Bot, DollarSign, Gauge, MessageSquare, Wrench } from "lucide-react";
import { redirect } from "next/navigation";
import { getCurrentUserAndWorkspace } from "@/lib/data/workspace";
import { getProductionObservability } from "@/lib/observability/analytics";

export default async function ObservabilityPage() {
  const { workspace } = await getCurrentUserAndWorkspace();
  if (!workspace) redirect("/login");
  const data = await getProductionObservability(workspace.workspaceId, 7);
  return <main className="mx-auto max-w-7xl px-5 py-8 sm:px-8">
    <div className="mb-8 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-ink">Production Observability</p><h1 className="mt-1 font-display text-2xl font-semibold text-ink">See what your agents are actually doing</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate">Trace agent runs, monitor quality and cost, inspect tool failures, and turn production problems into actionable fixes.</p></div><div className="rounded-full border border-mist bg-surface px-3 py-1.5 text-xs text-slate">Last 7 days</div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Activity size={16}/>} label="Agent runs" value={data.totalRuns.toLocaleString()} detail={`${data.succeededRuns.toLocaleString()} succeeded`}/><Metric icon={<AlertTriangle size={16}/>} label="Error rate" value={`${data.errorRate}%`} detail={`${data.failedRuns} failed runs`} warn={data.errorRate>5}/><Metric icon={<Gauge size={16}/>} label="P95 latency" value={`${data.p95}ms`} detail={`Average ${data.avgLatency}ms`}/><Metric icon={<DollarSign size={16}/>} label="AI cost" value={`$${data.cost.toFixed(4)}`} detail={`${data.toolCalls} tool calls`}/></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-3"><section className="rounded-2xl border border-mist bg-surface p-5 lg:col-span-2"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-display text-lg font-semibold text-ink">Agent performance</h2><p className="text-xs text-slate">Production runs by agent</p></div><Bot size={18} className="text-slate"/></div><div className="space-y-4">{data.botPerformance.length===0?<Empty text="No production runs yet."/>:data.botPerformance.map(bot=><div key={bot.id} className="rounded-xl border border-mist p-4"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><Link href={`/dashboard/bots/${bot.id}/edit`} className="font-medium text-ink hover:text-ink">{bot.name}</Link><p className="text-xs text-slate">{bot.runs} runs · {bot.avgLatency}ms avg</p></div><span className={bot.errorRate>5?"rounded-full bg-danger/10 px-2 py-1 text-xs font-medium text-danger":"rounded-full bg-success/10 px-2 py-1 text-xs font-medium text-success"}>{bot.errorRate}% errors</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-mist"><div className="h-full rounded-full bg-signal" style={{width:`${Math.max(4,100-bot.errorRate)}%`}}/></div><div className="mt-2 flex justify-between text-[11px] text-slate"><span>Cost ${bot.cost.toFixed(4)}</span><span>{bot.status}</span></div></div>)}</div></section>
    <section className="rounded-2xl border border-mist bg-surface p-5"><h2 className="font-display text-lg font-semibold text-ink">Provider health</h2><p className="mb-5 text-xs text-slate">AI gateway performance</p><div className="space-y-4">{data.providers.length===0?<Empty text="No model activity yet."/>:data.providers.map(p=><div key={p.provider}><div className="flex items-center justify-between text-sm"><span className="font-medium text-ink">{p.provider}</span><span className="text-slate">{p.requests} requests</span></div><div className="mt-2 h-2 rounded-full bg-mist"><div className="h-full rounded-full bg-signal" style={{width:`${Math.max(6,100-Math.round(p.failures/p.requests*100))}%`}}/></div><div className="mt-1 flex justify-between text-[11px] text-slate"><span>{p.avgLatency}ms avg</span><span>${p.cost.toFixed(4)}</span></div></div>)}</div></section></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-3"><section className="rounded-2xl border border-mist bg-surface p-5"><h2 className="font-display text-lg font-semibold text-ink">Quality signals</h2><div className="mt-4 grid grid-cols-2 gap-3"><Mini label="Helpful" value={data.satisfaction===null?"—":`${data.satisfaction}%`}/><Mini label="Tool failures" value={`${data.toolFailureRate}%`}/><Mini label="Successful runs" value={`${data.totalRuns?Math.round(data.succeededRuns/data.totalRuns*100):0}%`}/><Mini label="P95 latency" value={`${data.p95}ms`}/></div></section><section className="rounded-2xl border border-mist bg-surface p-5"><div className="flex items-center gap-2"><Wrench size={16} className="text-slate"/><h2 className="font-display text-lg font-semibold text-ink">Tool health</h2></div><p className="mt-2 text-sm text-slate">{data.toolFailures} failed tool executions out of {data.toolCalls}.</p><div className="mt-4 h-3 rounded-full bg-mist"><div className="h-full rounded-full bg-ember" style={{width:`${data.toolFailureRate}%`}}/></div><p className="mt-2 text-xs text-slate">{data.toolFailureRate}% failure rate</p></section><section className="rounded-2xl border border-mist bg-surface p-5"><div className="flex items-center gap-2"><MessageSquare size={16} className="text-slate"/><h2 className="font-display text-lg font-semibold text-ink">Business outcomes</h2></div><div className="mt-4 space-y-2">{Object.keys(data.business).length===0?<Empty text="No business events tracked yet."/>:Object.entries(data.business).map(([k,v])=><div key={k} className="flex justify-between rounded-lg bg-paper px-3 py-2 text-sm"><span className="capitalize text-slate">{k}</span><span className="font-medium text-ink">{v}</span></div>)}</div></section></div>
    <section className="mt-6 overflow-hidden rounded-2xl border border-mist bg-surface"><div className="border-b border-mist px-5 py-4"><h2 className="font-display text-lg font-semibold text-ink">Recent production runs</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-paper text-xs text-slate"><tr><th className="px-4 py-3">Run</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Model</th><th className="px-4 py-3">Steps</th><th className="px-4 py-3">Latency</th><th className="px-4 py-3">Cost</th></tr></thead><tbody>{data.recentRuns.map(r=><tr key={r.id} className="border-t border-mist"><td className="px-4 py-3"><Link href={`/dashboard/observability/${r.id}`} className="font-mono text-xs text-ink hover:underline">{r.id.slice(0,8)}</Link></td><td className="px-4 py-3"><span className={r.status==="succeeded"?"text-success":"text-danger"}>{r.status}</span></td><td className="px-4 py-3 text-slate">{r.provider||"—"} / {r.model||"—"}</td><td className="px-4 py-3 text-slate">{r.total_steps}</td><td className="px-4 py-3 text-slate">{r.duration_ms||0}ms</td><td className="px-4 py-3 text-slate">${Number(r.estimated_cost_usd||0).toFixed(5)}</td></tr>)}</tbody></table></div></section>
  </main>;
}
function Metric({icon,label,value,detail,warn=false}:{icon:React.ReactNode;label:string;value:string;detail:string;warn?:boolean}){return <div className="rounded-2xl border border-mist bg-surface p-5"><div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-slate">{icon}{label}</div><p className={`mt-1 font-display text-2xl font-semibold ${warn?"text-ember":"text-ink"}`}>{value}</p><p className="mt-1 text-xs text-slate">{detail}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-paper p-3"><p className="text-[11px] text-slate">{label}</p><p className="mt-1 font-display text-lg font-semibold text-ink">{value}</p></div>}
function Empty({text}:{text:string}){return <p className="rounded-lg border border-dashed border-mist p-4 text-center text-sm text-slate">{text}</p>}
