import { redirect } from "next/navigation";
import Link from "next/link";
import { Database, FileCheck2, ShieldCheck, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { getCurrentUserAndWorkspace } from "@/lib/data/workspace";
import { getOrganizationForWorkspace } from "@/lib/enterprise";
import { updatePrivacySettings, createDataSubjectRequest, updateDataSubjectRequest } from "@/lib/actions/privacy";
import { FormMessage } from "@/components/form-message";

export const dynamic = "force-dynamic";

export default async function PrivacyPage({ searchParams }: { searchParams: { error?: string; success?: string } }) {
  const { user, workspace } = await getCurrentUserAndWorkspace();
  if (!user || !workspace) redirect("/login");
  const org = await getOrganizationForWorkspace(workspace.workspaceId);
  if (!org) redirect("/dashboard/organization");
  const supabase = createClient();
  const [{ data: settings }, { data: requests }] = await Promise.all([
    supabase.from("organization_privacy_settings").select("pii_detection_enabled,redact_sensitive_logs,consent_required_for_training,data_residency").eq("organization_id", org.id).maybeSingle(),
    supabase.from("organization_data_subject_requests").select("id,request_type,status,reason,requested_at,completed_at").eq("organization_id", org.id).order("requested_at", { ascending: false }).limit(25),
  ]);
  const s = settings ?? { pii_detection_enabled: true, redact_sensitive_logs: true, consent_required_for_training: true, data_residency: "global" };
  return <main className="mx-auto max-w-6xl px-6 py-8">
    <div className="mb-6 flex items-end justify-between gap-4"><div><p className="mb-1 flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-ink"><ShieldCheck size={14}/> Privacy & data governance</p><h1 className="font-display text-2xl font-semibold text-ink">Privacy Center</h1><p className="mt-1 text-sm text-slate">Control data handling, privacy requests and governance policies for {org.name}.</p></div><Link href="/dashboard/organization/security-center" className="rounded-lg border border-mist bg-surface px-3 py-2 text-xs font-medium">Security Center</Link></div>
    <div className="mb-6"><FormMessage error={searchParams.error} success={searchParams.success}/></div>
    <section className="mb-6 rounded-2xl border border-mist bg-surface p-5"><div className="mb-4 flex items-center gap-2"><Database size={18}/><h2 className="font-medium">Data governance controls</h2></div><form action={updatePrivacySettings} className="grid gap-4 md:grid-cols-2"><label className="flex items-center justify-between rounded-lg border border-mist p-3 text-sm"><span>Detect PII in AI inputs/logs</span><input type="checkbox" name="pii_detection_enabled" defaultChecked={s.pii_detection_enabled}/></label><label className="flex items-center justify-between rounded-lg border border-mist p-3 text-sm"><span>Redact sensitive log content</span><input type="checkbox" name="redact_sensitive_logs" defaultChecked={s.redact_sensitive_logs}/></label><label className="flex items-center justify-between rounded-lg border border-mist p-3 text-sm"><span>Require consent for training use</span><input type="checkbox" name="consent_required_for_training" defaultChecked={s.consent_required_for_training}/></label><label className="rounded-lg border border-mist p-3 text-sm"><span className="mb-2 block">Data residency preference</span><select name="data_residency" defaultValue={s.data_residency} className="bg-surface text-ink w-full rounded-md border border-mist px-3 py-2"><option value="global">Global</option><option value="us">United States</option><option value="eu">European Union</option></select></label><div className="md:col-span-2"><button className="rounded-md bg-ink px-4 py-2 text-sm font-medium text-paper">Save privacy policy</button></div></form><p className="mt-3 text-xs text-slate">Residency preference is a governance setting; actual storage residency depends on enabled infrastructure providers and deployment configuration.</p></section>
    <section className="mb-6 rounded-2xl border border-mist bg-surface p-5"><div className="mb-4 flex items-center gap-2"><FileCheck2 size={18}/><h2 className="font-medium">Data subject request</h2></div><form action={createDataSubjectRequest} className="grid gap-3 md:grid-cols-[220px_1fr_auto]"><select name="request_type" className="bg-surface text-ink rounded-md border border-mist px-3 py-2 text-sm"><option value="export">Export my data</option><option value="access">Access my data</option><option value="deletion">Request deletion</option><option value="rectification">Request correction</option><option value="restriction">Restrict processing</option></select><input name="reason" placeholder="Optional reason or details" className="bg-surface text-ink rounded-md border border-mist px-3 py-2 text-sm"/><button className="rounded-md bg-ink px-4 py-2 text-sm font-medium text-paper">Submit request</button></form><p className="mt-3 text-xs text-slate">Requests enter a tracked review workflow. Destructive deletion should be executed only after authorization and dependency checks.</p></section>
    <section className="rounded-2xl border border-mist bg-surface p-5"><div className="mb-4 flex items-center gap-2"><Trash2 size={18}/><h2 className="font-medium">Privacy request queue</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-mist text-xs text-slate"><tr><th className="py-2">Requested</th><th>Type</th><th>Status</th><th>Reason</th><th>Action</th></tr></thead><tbody>{(requests ?? []).map(r=><tr key={r.id} className="border-b border-mist last:border-0"><td className="py-3 text-xs text-slate">{new Date(r.requested_at).toLocaleString()}</td><td className="capitalize">{r.request_type}</td><td className="capitalize">{r.status}</td><td className="max-w-xs truncate text-xs text-slate">{r.reason ?? "—"}</td><td>{r.status === "pending" ? <div className="flex gap-2"><form action={updateDataSubjectRequest.bind(null, r.id)}><input type="hidden" name="status" value="processing"/><button className="rounded border border-mist px-2 py-1 text-xs">Process</button></form><form action={updateDataSubjectRequest.bind(null, r.id)}><input type="hidden" name="status" value="completed"/><button className="rounded bg-signal/10 px-2 py-1 text-xs text-ink">Complete</button></form><form action={updateDataSubjectRequest.bind(null, r.id)}><input type="hidden" name="status" value="rejected"/><button className="rounded bg-danger/10 px-2 py-1 text-xs text-danger">Reject</button></form></div> : <span className="text-xs text-slate">No action</span>}</td></tr>)}{!(requests ?? []).length && <tr><td colSpan={5} className="py-8 text-center text-sm text-slate">No privacy requests yet.</td></tr>}</tbody></table></div></section>
  </main>;
}
