import { redirect } from "next/navigation";
import { ShieldCheck, KeyRound, Globe2, LockKeyhole } from "lucide-react";
import { getCurrentUserAndWorkspace } from "@/lib/data/workspace";
import { getOrganizationForWorkspace } from "@/lib/enterprise";
import { listIdentityConfig } from "@/lib/enterprise-identity";
import { addDomain, createScimToken, revokeScimToken, updateSecuritySettings } from "@/lib/actions/enterprise-identity";
import { createAdminClient } from "@/lib/supabase/admin";
import { FormMessage } from "@/components/form-message";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default async function EnterpriseSecurityPage({ searchParams }: { searchParams: { error?: string; success?: string; scimToken?: string } }) {
  const { user, workspace } = await getCurrentUserAndWorkspace();
  if (!user || !workspace) redirect("/login");
  const org = await getOrganizationForWorkspace(workspace.workspaceId);
  if (!org) redirect("/dashboard/settings?error=Organization+not+configured");
  const identity = await listIdentityConfig(org.id);
  const admin = createAdminClient();
  const { data: tokens } = await admin.from("organization_scim_tokens").select("id,name,created_at,last_used_at,expires_at,revoked_at").eq("organization_id", org.id).order("created_at", { ascending: false });
  const security = identity.security ?? { require_mfa: false, enforce_sso: false, restrict_to_verified_domains: false, ip_allowlist: [], session_timeout_minutes: 480 };
  return <main className="mx-auto max-w-5xl px-6 py-8">
    <div className="mb-6 flex items-start justify-between gap-4"><div><p className="mb-1 flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-ink"><ShieldCheck size={14}/> Enterprise security</p><h1 className="font-display text-2xl font-semibold text-ink">Identity & security</h1><p className="mt-1 text-sm text-slate">Configure SSO, domain controls, SCIM provisioning and organization security policies.</p></div><Link href="/dashboard/organization/security-center" className="shrink-0 whitespace-nowrap rounded-lg border border-mist bg-surface px-3.5 py-2 text-sm font-medium text-ink hover:border-signal/40">View audit trail →</Link></div>
    <FormMessage error={searchParams.error} success={searchParams.success}/>
    {searchParams.scimToken && <div className="my-5 rounded-xl border border-amber-300 bg-amber-50 p-4"><p className="text-sm font-semibold text-ink">Copy this SCIM token now</p><p className="mt-1 text-xs text-slate">It is only displayed once.</p><code className="mt-3 block break-all rounded-lg bg-surface p-3 text-xs">{searchParams.scimToken}</code></div>}
    <section className="mb-6 rounded-2xl border border-mist bg-surface p-5"><div className="mb-4 flex items-center gap-2"><LockKeyhole size={18}/><h2 className="font-medium text-ink">Organization security policy</h2></div><form action={updateSecuritySettings} className="grid gap-4 md:grid-cols-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="requireMfa" defaultChecked={security.require_mfa}/> Require MFA</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="enforceSso" defaultChecked={security.enforce_sso}/> Enforce SSO</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="restrictDomains" defaultChecked={security.restrict_to_verified_domains}/> Restrict sign-in to verified domains</label><label className="text-sm">Session timeout (minutes)<input name="sessionTimeout" type="number" min="15" max="10080" defaultValue={security.session_timeout_minutes} className="bg-surface text-ink mt-1 w-full rounded-md border border-mist px-3 py-2"/></label><label className="text-sm md:col-span-2">IP allowlist (one CIDR/IP per line)<textarea name="ipAllowlist" defaultValue={(security.ip_allowlist ?? []).join("\n")} className="bg-surface text-ink mt-1 min-h-24 w-full rounded-md border border-mist px-3 py-2 font-mono text-xs"/></label><button className="w-fit rounded-md bg-ink px-4 py-2 text-sm font-medium text-paper">Save policy</button></form></section>
    <section className="mb-6 rounded-2xl border border-mist bg-surface p-5"><div className="mb-4 flex items-center gap-2"><Globe2 size={18}/><h2 className="font-medium text-ink">Verified domains</h2></div><form action={addDomain} className="mb-4 flex gap-2"><input name="domain" required placeholder="company.com" className="bg-surface text-ink flex-1 rounded-md border border-mist px-3 py-2 text-sm"/><button className="rounded-md bg-ink px-4 py-2 text-sm font-medium text-paper">Add domain</button></form><div className="space-y-2">{identity.domains.map(d => <div key={d.id} className="flex items-center justify-between rounded-lg border border-mist px-3 py-3"><div><p className="text-sm font-medium">{d.domain}</p><p className="text-xs text-slate">Verification: {d.status}</p>{d.status === "pending" && <code className="text-[11px] text-slate">TXT chatbo-verification={d.verification_token ?? "hidden"}</code>}</div><span className="text-xs capitalize text-slate">{d.enforce_sso ? "SSO enforced" : "SSO optional"}</span></div>)}</div></section>
    <section className="mb-6 rounded-2xl border border-mist bg-surface p-5"><div className="mb-4 flex items-center gap-2"><KeyRound size={18}/><h2 className="font-medium text-ink">SSO configuration</h2></div><p className="text-sm text-slate">SAML 2.0 and OIDC configuration is stored server-side. Provider protocol adapters can be enabled when your identity provider metadata is supplied.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{identity.sso.map(s => <div key={s.id} className="rounded-lg border border-mist p-4"><p className="font-medium text-sm">{s.name}</p><p className="text-xs text-slate uppercase">{s.provider_type} · {s.enabled ? "enabled" : "disabled"}</p><p className="mt-2 text-xs text-slate">{s.issuer ?? s.entity_id ?? "Provider metadata not configured"}</p></div>)}{identity.sso.length === 0 && <div className="rounded-lg bg-paper p-4 text-sm text-slate">No enterprise SSO provider configured yet.</div>}</div></section>
    <section className="rounded-2xl border border-mist bg-surface p-5"><div className="mb-4 flex items-center gap-2"><KeyRound size={18}/><h2 className="font-medium text-ink">SCIM provisioning</h2></div><p className="mb-4 text-sm text-slate">Provision and deprovision users from your identity provider using the SCIM 2.0 API.</p><form action={createScimToken} className="mb-5 flex gap-2"><input name="name" placeholder="Okta / Entra SCIM" className="bg-surface text-ink flex-1 rounded-md border border-mist px-3 py-2 text-sm"/><button className="rounded-md bg-ink px-4 py-2 text-sm font-medium text-paper">Create token</button></form><div className="space-y-2">{(tokens ?? []).map(t => <div key={t.id} className="flex items-center justify-between rounded-lg border border-mist px-3 py-3"><div><p className="text-sm font-medium">{t.name}</p><p className="text-xs text-slate">Created {new Date(t.created_at).toLocaleString()} · {t.revoked_at ? "revoked" : t.last_used_at ? `Last used ${new Date(t.last_used_at).toLocaleString()}` : "never used"}</p></div>{!t.revoked_at && <form action={revokeScimToken.bind(null, t.id)}><button className="rounded-md border border-mist px-3 py-1.5 text-xs">Revoke</button></form>}</div>)}</div></section>
  </main>;
}
