import { createAdminClient } from "@/lib/supabase/admin";
import { getCurrentUserAndWorkspace } from "@/lib/data/workspace";
import { Clock3, ShieldCheck } from "lucide-react";
import { ApprovalActions } from "@/components/approvals/approval-actions";
export const dynamic = "force-dynamic";
export default async function ApprovalsPage() {
  const { workspace, user } = await getCurrentUserAndWorkspace();
  if (!workspace || !user) return null;
  const admin = createAdminClient();
  const { data: approvals } = await admin.from("workflow_approvals").select("id,workflow_id,workflow_run_id,node_id,title,description,action_type,approver_role,status,payload,requested_at,expires_at,decision_comment").eq("workspace_id", workspace.workspaceId).order("requested_at", { ascending: false }).limit(100);
  const pending = (approvals ?? []).filter(a => a.status === "pending");
  return <main className="mx-auto max-w-5xl px-6 py-8"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><ShieldCheck size={22}/><h1 className="font-display text-2xl font-semibold text-ink">Approval Center</h1></div><p className="mt-1 text-sm text-slate">Review sensitive AI and workflow actions before they reach customers or external systems.</p></div><div className="rounded-full bg-paper px-3 py-1 text-sm font-medium">{pending.length} pending</div></div><div className="mt-7 space-y-4">{(approvals ?? []).length ? approvals!.map(a => <article key={a.id} className="rounded-2xl border border-mist bg-surface p-5"><div className="flex items-start justify-between gap-5"><div className="flex gap-3"><Clock3 className="mt-1 text-slate" size={18}/><div><h2 className="font-semibold text-ink">{a.title}</h2><p className="mt-1 text-sm text-slate">{a.description || "No additional description."}</p><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate"><span className="rounded-full bg-paper px-2 py-1">{a.action_type}</span><span className="rounded-full bg-paper px-2 py-1">Requires {a.approver_role}</span><span className="rounded-full bg-paper px-2 py-1">{new Date(a.requested_at).toLocaleString()}</span></div></div></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${a.status === "approved" ? "bg-success/10 text-success" : a.status === "rejected" ? "bg-danger/10 text-danger" : "bg-paper text-slate"}`}>{a.status}</span></div>{a.status === "pending" && <div className="mt-4 border-t border-mist pt-4"><div className="mb-3 rounded-lg bg-paper p-3"><div className="text-xs font-semibold uppercase tracking-wide text-slate">Action payload</div><pre className="mt-2 max-h-48 overflow-auto text-xs text-ink">{JSON.stringify(a.payload, null, 2)}</pre></div><ApprovalActions approvalId={a.id} title={a.title} /></div>}</article>) : <div className="rounded-xl border border-dashed border-mist bg-surface p-12 text-center"><ShieldCheck className="mx-auto text-ink" size={32}/><h2 className="mt-3 font-semibold">No approval requests</h2><p className="mt-1 text-sm text-slate">Sensitive workflow actions will appear here when an agent needs human authorization.</p></div>}</div></main>;
}
